# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing with Node, read the docs:
# https://circleci.com/docs/language-javascript/ for more details
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/node
      - image: cimg/node:16.20.1

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - node/install-packages:
          override-ci-command: npm install --legacy-peer-deps
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test

  build:
    docker:
      - image: cimg/node:16.20.1
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install --legacy-peer-deps
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: out
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:16.20.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:5aE7AmvtKBZR+3Zs0AakVuWjtQ+oRAiw3k714FR/KeU'
      - attach_workspace:
          at: /tmp/out
      - checkout
      - run:
          name: Deploy to GitHub Pages
          command: |
            git fetch
            git checkout gh-pages
            rm -rf ./*
            mv /tmp/out/* .
            touch .nojekyll
            git config user.email "1903291+hex22a@users.noreply.github.com"
            git config user.name "CircleCI (on behalf of Crash)"
            git add .
            git commit -m "CircleCI deploy to GitHub Pages"
            git push -u origin gh-pages
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy-gh-pages: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - gh-pages
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
      - build:
          filters:
            tags:
              only: /^\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          requires:
            - test

      - deploy:
          filters:
            tags:
              only: /^\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          requires:
            - test
            - build
